In [1]:
import numpy as np

In [7]:
a = np.array([2,4,6])
b = np.array([2,6,6])
np.add(a,b)
np.subtract(a,b)    

array([ 0, -2,  0])

In [9]:
print(np.greater(b,a))

[False  True False]


In [10]:
print(np.less(b,a))

[False False False]


In [11]:
print(np.greater_equal(b,a))

[ True  True  True]


In [14]:
print(np.less_equal(b,a))

[ True False  True]


In [17]:
#array of even numbers from 30 to 70

even = np.arange(30,71,2)
print(even)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [19]:
#print identity matrix

id = np.identity(5)
print(id)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [20]:
#changing thye sign of numbers in a specific range

x = np.arange(21)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [21]:
#we have to change sign of number from 9 to 15

x[(x>=9)&(x<=15)] *= -1
print(x)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [22]:
#diagonal matrix with elemenmts 12345

x = np.diag([1,2,3,4,5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [27]:
# matrix operations

x = np.array([[1,2,3],[4,5,6],[2,6,3]])
y = np.array([[4,2,6],[7,9,8],[4,3,8]])

print(np.add(x,y))

[[ 5  4  9]
 [11 14 14]
 [ 6  9 11]]


In [26]:
print(np.sqrt(x))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [28]:
print(x.T)

[[1 4 2]
 [2 5 6]
 [3 6 3]]


In [31]:
print(np.dot(x,y))

[[ 30  29  46]
 [ 75  71 112]
 [ 62  67  84]]


In [36]:
print(np.sum(y,axis=1))

[12 24 15]
